[package]

name = "ecc"
description = "An elliptic curve arithmetic and cryptography library."
version = "0.1.1"
authors = ["Thomas SAVIO <ytulf@pm.me>"]
license = "MIT"

[dependencies.num]
version = "0.1.0"
